import { 
  Check, 
  X, 
  BarChart2, 
  Target, 
  Building, 
  Wallet, 
  Briefcase, 
  User, 
  Settings, 
  LogOut, 
  LogIn, 
  Menu, 
  Home, 
  CreditCard, 
  PiggyBank, 
  DollarSign, 
  Bell, 
  Calendar, 
  Loader2, 
  ChevronDown, 
  ArrowLeft, 
  ArrowRight, 
  Plus, 
  Pencil, 
  Trash,
  FileText,
  Download,
  Upload,
  Send,
  Search,
  Filter,
  Moon,
  Sun,
  Mic,
  Star,
  Heart,
  Clock
} from "lucide-react";

export const Icons = {
  check: Check,
  close: X,
  chart: BarChart2,
  goal: Target,
  bank: Building,
  wallet: Wallet,
  briefcase: Briefcase,
  user: User,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  menu: Menu,
  home: Home,
  card: CreditCard,
  savings: PiggyBank,
  dollar: DollarSign,
  notification: Bell,
  calendar: Calendar,
  spinner: Loader2,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  add: Plus,
  edit: Pencil,
  delete: Trash,
  file: FileText,
  download: Download,
  upload: Upload,
  send: Send,
  search: Search,
  filter: Filter,
  dark: Moon,
  light: Sun,
  voice: Mic,
  star: Star,
  favorite: Heart,
  time: Clock
};

export default Icons;